### ISSUE TITLE
Setup a Mastodon instance

### ISSUE THREAD

**Issue by techhead** [techhead/techhead#2]
I think that the Fediverse is very important. I plan to blog about it. I wanted to build it before I was aware that it already existed. Now I want to help built it.

https://joinmastodon.org/

Here's an excellent intro article by @revmischa.

https://dev.to/cybermischa/decentralizing-social-media-31e3

I plan to set up a public instance running a forked version of Mastodon and curate new features based on user feedback. I bought the domain [tusked.net](https://tusked.net) for this purpose. I'll update this issue when it's up and ready for signups.

**Comment by revmischa** [comment]
https://discord.gg/Djfxv6JR i want to do more messing around with activitypub
